In [4]:
import pandas as pd

In [10]:
# creating DataFrame

df1 = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul"],
    "Marks": [85, 92, 78]
})
df1


df2 = pd.DataFrame([
    ["Aman", 85],
    ["Riya", 92],
    ["Rahul", 78]
], columns=["Name", "Marks"])
df2


df3 = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [19, 20, 19],
    "Marks": [80, 90, 85]
})
df3

  Name  Age  Marks
0    A   19     80
1    B   20     90
2    C   19     85

In [13]:
# head function - shows top few rows

df.head()

df.head(2)

df.head(4)

    Name  Marks  Age
0   Aman     85   19
1   Riya     92   20
2  Rahul     78   19

In [15]:
# tail function - shows last few rows

df.tail()

df.tail(2)

df.tail(4)

    Name  Marks  Age
0   Aman     85   19
1   Riya     92   20
2  Rahul     78   19

In [21]:
# info function - shows columns and data types.

df.info()

df[["Name", "Marks"]].info()

df[["Age", "Marks"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Marks   3 non-null      int64
 2   Age     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Marks   3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     3 non-null      int64
 1   Marks   3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [20]:
# describe function - shows numeric data details

df.describe()

df["Marks"].describe()

df[["Age", "Marks"]].describe()

             Age  Marks
count   3.000000    3.0
mean   19.333333   85.0
std     0.577350    7.0
min    19.000000   78.0
25%    19.000000   81.5
50%    19.000000   85.0
75%    19.500000   88.5
max    20.000000   92.0

In [22]:
# shape function - shows rows and columns 

df.shape

df.shape[0]

df.shape[1]

3

In [23]:
# columns function - returns list of columns 

df.columns

list(df.columns)

df.columns.tolist()

['Name', 'Marks', 'Age']

In [ ]:
# drop function - removes row or column
df.drop("Age", axis=1)

df.drop(columns=["Age"])

df.drop(index=0)

In [ ]:
# isnull function - checks if the value is null

df.isnull()

df["Marks"].isnull()

df.isnull().sum()

In [ ]:
# sum functiomn - gives the sum 

df["Marks"].sum()

df[["Age", "Marks"]].sum()

df.sum(numeric_only=True)

In [24]:
# mean and median functions

df["Marks"].mean()

df["Age"].mean()

df[["Age", "Marks"]].mean()

df["Marks"].median()

df["Age"].median()

df[["Age", "Marks"]].median()

Age      19.0
Marks    85.0
dtype: float64

In [ ]:
# min and max functions - returns minimum or maximum

df["Marks"].min()

df["Age"].min()

df[["Age", "Marks"]].min()

df["Marks"].max()

df["Age"].max()

df[["Age", "Marks"]].max()

In [ ]:
# std and var functiom - gives standard deviation and variance 
df["Marks"].std()

df["Age"].std()
 
df[["Age", "Marks"]].std()

df["Marks"].var()

# Example 
df["Age"].var()

df[["Age", "Marks"]].var()

In [ ]:
# cconcat function - combines dataframes
pd.concat([df1, df2])

pd.concat([df1, df2], ignore_index=True)

pd.concat([df1, df2], axis=1)

In [ ]:
# read_csv function - reads a csv file 
data = pd.read_csv("students.csv")
data

# Example 2
data = pd.read_csv("students.csv", nrows=5)
data

# Example 3
data = pd.read_csv("students.csv", usecols=["Name", "Marks"])
data